hidden_size:      128
learning_rate:    0.0003
gamma:            0.99
clip_epsilon:     0.2  
k_epochs:         4
gae_lambda:       0.95   
entropy_coef:     0.01
value_loss_coef:  0.5
max_grad_norm:    0.5      
update_timestep:  4000
model_path:       "models/ppo.pth"

num_episodes:     2000
print_freq:       100
save_freq:        100
recorder:         true   
